### ISSUE TITLE
Neku Sprite is missing

### ISSUE THREAD

**Issue by Cinnayanny** [errantSquam/twewy-message-generator#2]
![TWEWY_Screencap(1)](https://github.com/eLTehh/twewy-message-generator/assets/87155393/1f648215-3104-4ff8-a5ac-27a07781e13e)

So, I'm here to alert that there is a sprite missing
![image](https://github.com/eLTehh/twewy-message-generator/assets/87155393/0688f9ca-a39e-4a8a-b8ba-f97b2818cf6c)

This sprite, in particular.
May you please add it?

Thank you

**Comment by errantSquam** [comment]
It is indeed missing, thank you for the report! I will get to it in a sec.

**Comment by errantSquam** [comment]
He has been added! Shouldn't have any issues. Thank you for the report!

**Comment by Cinnayanny** [comment]
Thank you!
